//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CallMon.rc
//
#define UNKNOWN_STATUS                  0
#define OFFLINE_STATUS                  1
#define ONLINE_STATUS                   2
#define BUSY_STATUS                     3
#define IDBROWSE                        3
#define DIALING_STATUS                  4
#define FREEING_STATUS                  5
#define ID_CALLVIEW                     101
#define IDB_OFFLINE                     102
#define IDB_ONLINE                      103
#define IDB_DIALING                     105
#define IDB_BUSY                        106
#define ID_PROPERTY                     106
#define ID_PARAMETERS                   107
#define IDR_MAINMENU                    109
#define ID_HOSTLIST                     110
#define IDB_BYTEL1                      113
#define IDB_BYTEL                       113
#define ID_FILES                        114
#define ID_BOUYGUES                     115
#define CALLMON_OFF                     116
#define ID_COUNTERS                     118
#define CALLMON_ON                      120
#define ID_PROPERTIES                   121
#define ID_SELECT                       123
#define ID_EMERGENCY                    124
#define IDR_SHORTCUTS                   125
#define ID_TCPIP                        126
#define CCH_MAXITEMTEXT                 256
#define IDSTART                         1008
#define IDSTOP                          1009
#define ID_STATUS                       1017
#define IDC_MSISDN                      1018
#define IDC_RECORD                      1019
#define IDC_VDN                         1021
#define IDC_CALLS                       1022
#define IDC_VECTOR                      1023
#define IDC_MAXCALLS                    1024
#define IDC_DURATION                    1025
#define IDC_CALLDURATION                1026
#define IDC_DIALING                     1027
#define IDC_DIALINGDELAY                1028
#define IDC_BUSY                        1029
#define IDC_BUSYDELAY                   1030
#define IDC_FREEING                     1031
#define IDC_FREEINGDELAY                1032
#define IDC_TIMEOUT                     1033
#define IDC_MESSAGE                     1033
#define IDC_CALLTIMEOUT                 1034
#define IDC_LOOP                        1034
#define IDC_INFO                        1036
#define IDC_HOSTLOGO                    1038
#define IDC_HOSTNAME                    1039
#define IDC_SELECT                      1040
#define IDC_WARNING                     1043
#define IDC_FILENAME                    1044
#define IDC_LOOPTEXT                    1045
#define IDC_WHO                         1047
#define IDC_WHOTITLE                    1048
#define IDC_COPYRIGHT                   1050
#define IDC_SERVICES                    1051
#define IDC_SERVERS                     1052
#define IDC_HOSTINPUT                   1053
#define IDC_HOSTGROUP                   1054
#define IDC_SERVICESGROUP               1055
#define IDC_SEPARATOR                   1056
#define IDC_BAR16                       1057
#define IDC_BAR10                       1058
#define IDM_MSISDN                      1058
#define IDC_BAR13                       1059
#define IDM_TIMEOUT                     1059
#define IDC_BAR12                       1060
#define IDM_MSISDNLOCK                  1060
#define IDC_BAR15                       1061
#define IDM_TIMEOUTLOCK                 1061
#define IDC_BAR14                       1062
#define IDC_SELECT_FROM                 1062
#define IDC_BAR11                       1063
#define IDC_SELECT_TO                   1063
#define IDC_BAR23                       1064
#define IDC_EDIT_FROM                   1064
#define IDC_BAR21                       1065
#define IDC_EDIT_TO                     1065
#define IDC_BAR22                       1066
#define IDC_CNXLOST                     1066
#define IDC_BAR20                       1067
#define IDC_NICKNAMES                   1067
#define IDC_BAR24                       1068
#define IDC_BAR25                       1069
#define IDC_BAR26                       1070
#define IDC_PORT1                       1070
#define IDC_BAR33                       1071
#define IDC_PORT2                       1071
#define IDC_BAR31                       1072
#define IDC_PORT3                       1072
#define IDC_BAR32                       1073
#define IDC_BAR30                       1074
#define IDC_BAR34                       1075
#define IDC_BAR35                       1076
#define IDC_BAR36                       1077
#define WP_UPDATE                       3000
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_EXIT                    40005
#define ID_ACTION_START                 40009
#define ID_ACTION_STOP                  40010
#define ID_ACTION_CONNECT               40012
#define ID_ACTION_DISCONNECT            40013
#define ID_OPTION_TELEPHONY             40014
#define ID_FILE_DELETE                  40018
#define ID_OPTION_DEBUG                 40023
#define ID_ABOUT                        40024
#define ID_EDIT_PROPERTIES              40027
#define ID_EDIT_SELECT_FROMTO           40031
#define ID_EDIT_SELECT_CLEAR            40032
#define ID_TIMING                       40035
#define ID_OPTION_TCPIP                 40036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
